volumes:
  databasevolume:
  rabbitmqvolume:

networks:
  fazumpix:
    name: fazumpix
    driver: bridge

services:
  database:
    image: postgres
    container_name: postgresql
    networks:
      - fazumpix
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "databasevolume:/var/lib/postgresql/data"

  queue:
    image: rabbitmq:3.13-management
    container_name: queue
    networks:
      - fazumpix
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=mq
    volumes:
      - rabbitmqvolume:/var/lib/rabbitmq

  api:
    image: fazumpix-api
    build: .
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - fazumpix
    depends_on:
      - database
    environment:
      - CONNECTIONSTRINGS__DATABASE=Host=database;Port=5432;Username=postgres;Password=postgres;Database=fazumpix
  #
  # TODO: Fix migrations
  #
  # migrations:
  #   image: fazumpix-migrations
  #   build:
  #     context: .
  #     dockerfile: dockerfile.migrations
  #   container_name: migrations
  #   environment:
  #     - CONNECTIONSTRINGS__DATABASE=Host=database;Port=5432;Username=postgres;Password=postgres;Database=fazumpix
